language: node_js
node_js:
  - 12.14.0

after_success: 
  - npm run coverage
  - npm run build

before_deploy: 
  - node before_deploy.js
  - cd dist
  - ls

deploy:
  provider: npm
  email: joao.menighin@gmail.com
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  edge: true
  on:
    branch: master